"""init_data

Revision ID: 4e9c1e2d7248
Revises: 
Create Date: 2026-01-22 02:32:45.612436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e9c1e2d7248"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column(
            "uuid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique UUID",
        ),
        sa.Column("user_uuid", sa.BigInteger(), nullable=True),
        sa.Column(
            "first_name",
            sa.String(length=50),
            nullable=True,
            comment="Фамилия",
        ),
        sa.Column(
            "last_name", sa.String(length=50), nullable=True, comment="Имя"
        ),
        sa.Column(
            "second_name",
            sa.String(length=50),
            nullable=True,
            comment="Отчество",
        ),
        sa.Column(
            "birth_day", sa.Date(), nullable=True, comment="Дата рождения"
        ),
        sa.Column(
            "class_number", sa.Integer(), nullable=True, comment="Номер класса"
        ),
        sa.Column(
            "class_parallel",
            sa.String(length=1),
            nullable=True,
            comment="Параллель",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_students")),
        sa.UniqueConstraint("user_uuid", name=op.f("uq_students_user_uuid")),
    )
    op.create_table(
        "teachers",
        sa.Column(
            "uuid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique UUID",
        ),
        sa.Column("user_uuid", sa.BigInteger(), nullable=True),
        sa.Column(
            "first_name",
            sa.String(length=50),
            nullable=True,
            comment="Фамилия",
        ),
        sa.Column(
            "last_name", sa.String(length=50), nullable=True, comment="Имя"
        ),
        sa.Column(
            "second_name",
            sa.String(length=50),
            nullable=True,
            comment="Отчество",
        ),
        sa.Column(
            "birth_day", sa.Date(), nullable=True, comment="Дата рождения"
        ),
        sa.Column(
            "employment_date",
            sa.Date(),
            nullable=True,
            comment="Дата трудоустройства",
        ),
        sa.Column(
            "total_years_at_hire",
            sa.Integer(),
            nullable=True,
            comment="Общий стаж (лет) на дату приема",
        ),
        sa.Column(
            "total_months_at_hire",
            sa.Integer(),
            nullable=True,
            comment="Общий стаж (месяцев) на дату приема",
        ),
        sa.Column(
            "total_days_at_hire",
            sa.Integer(),
            nullable=True,
            comment="Общий стаж (дней) на дату приема",
        ),
        sa.Column(
            "teacher_years_at_hire",
            sa.Integer(),
            nullable=True,
            comment="Педагогический стаж (лет) на дату приема",
        ),
        sa.Column(
            "teacher_months_at_hire",
            sa.Integer(),
            nullable=True,
            comment="Педагогический стаж (месяцев) на дату приема",
        ),
        sa.Column(
            "teacher_days_at_hire",
            sa.Integer(),
            nullable=True,
            comment="Педагогический стаж (дней) на дату приема",
        ),
        sa.Column(
            "education",
            sa.String(length=50),
            nullable=True,
            comment="Образование",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_teachers")),
        sa.UniqueConstraint("user_uuid", name=op.f("uq_teachers_user_uuid")),
    )
    op.create_table(
        "users",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_users")),
        sa.UniqueConstraint("user_id", name=op.f("uq_users_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("teachers")
    op.drop_table("students")
    # ### end Alembic commands ###
